#!/usr/bin/env python

from __future__ import print_function

import os
import sys

import sr

if len(sys.argv) < 2:
    exit("Usage: student-to-teacher USERNAME")

UNAMES = sys.argv[1:]

missing = [uname for uname in UNAMES if not sr.user.exists(uname)]
if any(missing):
    print("User(s) '%s' do no exist." % "', '".join(missing), file=sys.stderr)
    print("No changes made.", file=sys.stderr)
    exit(1)

for UNAME in UNAMES:
    u = sr.user(UNAME)

    students = sr.group("students")
    assert students.in_db
    students.user_rm( UNAME )
    students.save()

    teachers = sr.group("teachers")
    assert teachers.in_db
    teachers.user_add( UNAME )
    teachers.save()
