#!/usr/bin/env python

import os
import sys

import sr

if len(sys.argv) < 2:
    exit("Usage: student-to-teacher USERNAME")

UNAMES = sys.argv[1:]

for UNAME in UNAMES:
    u = sr.user(UNAME)

    if not u.in_db:
        exit("User \"%s\" does not exist." % UNAME)

for UNAME in UNAMES:
    u = sr.user(UNAME)

    students = sr.group("students")
    assert students.in_db
    students.user_rm( UNAME )
    students.save()

    teachers = sr.group("teachers")
    assert teachers.in_db
    teachers.user_add( UNAME )
    teachers.save()
