#!/usr/bin/env python
import sys, getpass
import c_user, c_group, c_teams

commands = { "college": c_teams.CmdColleges,
             "group": c_group.group,
             "team": c_teams.CmdTeams,
             "user": c_user.user }

def usage():
    print """Usage:
    %s command command_args

    Where command is one of:""" % sys.argv[0]

    for c in commands.keys():
        print "\t%s" % c

    print """Type %s COMMAND help to get more information.""" % sys.argv[0]

def c_help(args):
    global commands

    if len(args) == 0:
        usage()
        return

    if args[0] in commands:
        print commands[args[0]].__doc__

    sys.exit(0)

def exec_cmd(args):
    cmd = args[0]

    if cmd in commands.keys():
        commands[cmd]( args[1:] )
    else:
        print "Invalid command."
        usage()

if len(sys.argv) < 2:
    usage()
    sys.exit(1)

exec_cmd(sys.argv[1:])
